version: "3.7"
services:
  tailscale:
    container_name: tailscale-network
    image: tailscale/tailscale:latest
    hostname: $HOST_NAME
    environment:
      - TS_AUTHKEY=$AUTHKEY
      - TS_EXTRA_ARGS=$ARGS
      - TS_ROUTES=$ROUTES
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    devices:
      - "/dev/net/tun"
    volumes:
      - $STATE_DIR:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped