version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      internal_default:
        ipv4_address: $DOCKER_NETWORK_ADDRESS
    environment:
      TZ: $TZ
      WEBPASSWORD: $PASS
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    # Volumes store your data between container upgrades
    volumes:
      - $PIHOLE_DIR:/etc/pihole
      - $DNSMASQ_DIR:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks:
  internal_default:
    external: true

